version: '3.7'

services:
  aspnetcore-logging:
    networks:
    - aspnetcore-net
    
    # variable must be set before using the compose file
    image: ${IMAGE:-docker.io/ivansharamok/aspnetcore-docker-logging}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_DETAILEDERRORS=1
    ports:
    - target: 80
      published: 8000
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M
      placement:
        constraints:
        - node.platform.os == linux

networks:
  aspnetcore-net: