name: Build and Push to Docker Hub

on:
  # trigger on push to master branch but ignore specified paths
  push:
    branches:
      - master
    paths-ignore:
      - "**/az-*.yml"
  # trigger on pull request for master branch but ignore specified paths
  pull_request:
    paths-ignore:
      - "**/az-*.yml"
    branches:
      - master

jobs:
  build_and_push:
    # issue with 18.04 https://github.com/dotnet/core/issues/3312
    runs-on: ubuntu-16.04
    name: build and push Docker image
    steps:
      - name: checkout git repo
        uses: actions/checkout@master

      - name: login to Docker Hub
        uses: azure/container-actions/docker-login@master
        with:
          login-server: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build and push the image
        env:
          IMAGE: docker.io/ivansharamok/aspnetcore-docker-logging
        run: |
          docker-compose build
          docker-compose push
